import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/common/NavigationBar";
import Footer from "@/components/common/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-linear-to-b from-gray-950 via-[#031221] to-[#0C3966] min-h-screen flex flex-col justify-between`}
      >
        <NavigationBar />
        {children}
        <div className="w-full px-4 sm:px-5 pb-3">
          <Footer />
        </div>
      </body>
    </html>
  );
}
