export const service_data = [
  {
    service_name: "Fashion Design",
    service_desc: "End-to-end design built around your vision",
    serviceImages: [
      "/services/fashion-design/1.png",
      "/services/fashion-design/2.png",
      "/services/fashion-design/4.png",
      "/services/fashion-design/5.png",
      "/services/fashion-design/6.png",
      "/services/fashion-design/7.png",
      "/services/fashion-design/8.png",
      "/services/fashion-design/9.png",
      "/services/fashion-design/10.png",
    ],
  },
  {
    service_name: "E-commerce Imagery",
    service_desc: "High-impact visuals optimized for online sales",
    serviceImages: [
      "/services/ecomm-imagery/1.png",
      "/services/ecomm-imagery/2.png",
      "/services/ecomm-imagery/3.png",
    ],
  },
  {
    service_name: "Prints",
    service_desc: "Exclusive artworks designed for your brand",
    serviceImages: [
      "/services/prints/26SZ0363_312_1.png",
      "/services/prints/Blue Abstract-1.png",
      "/services/prints/Blue Tint groovy fluid-2.png",
      "/services/prints/CAWMG000_408_ALT4.png",
      "/services/prints/HVWSG000_451.png",
      "/services/prints/HVWSG003_479.png",
      "/services/prints/L-SLM_Repeat.jpg",
      "/services/prints/Lilac marble-1.png",
      "/services/prints/Soft pink marble-1.png",
    ],
  },
  {
    service_name: "Graphics",
    service_desc: "Custom graphic assets tailored to your identity",
    serviceImages: [
      "/services/graphics/1.jpeg",
      "/services/graphics/2.jpeg",
      "/services/graphics/4.jpg",
      "/services/graphics/5.jpg",
      "/services/graphics/6.jpg",
      "/services/graphics/7.jpg",
      "/services/graphics/8.jpg",
      "/services/graphics/9.jpg",
      "/services/graphics/10.jpg",
      "/services/graphics/11.jpg",
      "/services/graphics/12.jpg",
      "/services/graphics/13.jpg",
      "/services/graphics/14.jpg",
      "/services/graphics/15.jpg",
      "/services/graphics/16.jpg",
      "/services/graphics/17.jpg",
    ],
  },
  {
    service_name: "Virtual/Physical Fitting",
    service_desc: "Accurate fit visualization, digital to real",
    serviceImages: ["/services/virtual-fitting/001.jpg"],
  },
  {
    service_name: "Techpack Creations",
    service_desc: "Production-ready specifications with precision",
    serviceImages: [],
  },
];
